version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: deploy_mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=deploy_mongo_username
      - MONGO_INITDB_ROOT_PASSWORD=deploy_mongo_pwd
    ports:
      - "27018:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - type: volume
        source: mongodb_data
        target: /data/db
    networks:
      - mongo_network

networks:
  mongo_network:
    driver: bridge
volumes:
  mongodb_data: