version: "3.9"

x-application_standard: &application_standard
  image: demo:latest
  networks:
    - application
    - deploy_network

services:
  demo-app-blue:
    <<: *application_standard
    container_name: demo_app_blue
    environment:
      APPLICATION: blue
  demo-app-green:
    <<: *application_standard
    container_name: demo_app_green
    environment:
      APPLICATION: green

  nginx:
    image: nginx
    container_name: local_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - demo-app-blue
      - demo-app-green
    networks:
      - application

networks:
  application:
    driver: bridge
  deploy_network:
    driver: bridge
