version: "3.8"

x-application_standard: &application_standard
  image: demo:latest
  networks:
    - application
  extra_hosts:
    - host.docker.internal:172.18.0.1

services:
  demo-qa-app-blue:
    <<: *application_standard
    container_name: demo_qa_app_blue
    environment:
      APPLICATION: blue
  demo-qa-app-green:
    <<: *application_standard
    container_name: demo_qa_app_green
    environment:
      APPLICATION: green


  nginx:
    image: nginx
    container_name: local_nginx
    ports:
      - "82:80"
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/qa.conf
    depends_on:
      - demo-qa-app-blue
      - demo-qa-app-green
    networks:
      - application


networks:
  application:
    driver: bridge