version: "3.8"

x-application_standard: &application_standard
  image: demo:latest
  networks:
    - application
  extra_hosts:
    - host.docker.internal:172.18.0.1

services:
  demo-dev-app-blue:
    <<: *application_standard
    container_name: demo_dev_app_blue
    environment:
      APPLICATION: blue
  demo-dev-app-green:
    <<: *application_standard
    container_name: demo_dev_app_green
    environment:
      APPLICATION: green


  nginx:
    image: nginx
    container_name: dev_nginx
    ports:
      - "81:80"
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/dev.conf
    depends_on:
      - demo-dev-app-blue
      - demo-dev-app-green
    networks:
      - application


networks:
  application:
    driver: bridge