version: '3.8'

services:
  book-svc:
    build: ./book-svc
    container_name: book_svc
    networks:
      - backend_network
    depends_on:
      - mongodb

  bff:
    build: ./bff
    container_name: bff_service
    ports:
      - "3000:3000" # Expose bff on port 80 of the host
    networks:
      - backend_network
    depends_on:
      - book-svc

networks:
  backend_network:
    external: true
