version: '3.8'

services:
  book-svc:
    build: ./book-svc
    container_name: local_book_svc
    networks:
      - local_backend_network

  bff-svc:
    build: ./bff
    container_name: local_bff_svc
    ports:
      - "3000:3000" # Expose bff on port 80 of the host
    networks:
      - local_backend_network
    depends_on:
      - book-svc

networks:
  local_backend_network:
    external: true
