version: "3.8"
#PASS the APP_ENV by   APP_ENV="${SPRING_CONFIG_NAME}" docker-compose -f docker-compose.yml up -d --no-recreate
x-application_standard: &application_standard
  image: demo:latest
  networks:
    - application
  extra_hosts:
    - host.docker.internal:172.18.0.1
  environment:
    - APP_ENV=${APP_ENV}
    - NGINX_PORT=${NGINX_PORT}
    - MONGODB=URI=${MONGODB_URI}

services:
  demo-app-blue:
    <<: *application_standard
    container_name: demo_${APP_ENV}_app_blue
    environment:
      APPLICATION: blue
  demo-app-green:
    <<: *application_standard
    container_name: demo_${APP_ENV}_app_green
    environment:
      APPLICATION: green


  nginx:
    image: nginx
    container_name: ${APP_ENV}_nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./nginx/${APP_ENV}/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - demo-app-blue
      - demo-app-green
    networks:
      - application


networks:
  application:
    driver: bridge