version: "3.8"

x-application_standard: &application_standard
  image: demo:latest
  networks:
    - application
  extra_hosts:
    - host.docker.internal:172.18.0.1

services:
  demo-app-blue:
    <<: *application_standard
    container_name: demo_app_blue
    environment:
      APPLICATION: blue
  demo-app-green:
    <<: *application_standard
    container_name: demo_app_green
    environment:
      APPLICATION: green


  nginx:
    image: nginx
    container_name: local_nginx
    ports:
      - "81:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - demo-app-blue
      - demo-app-green
    networks:
      - application


networks:
  application:
    driver: bridge