version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: dev_mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=dev_mongo_username
      - MONGO_INITDB_ROOT_PASSWORD=dev_mongo_pwd
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - type: volume
        source: mongodb_data
        target: /data/db
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  mongodb_data:
