version: "3.8"
services:
  dev_nginx:
    image: nginx
    container_name: dev_nginx
    ports:
      - "81:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - application
networks:
  application:
    driver: bridge