@Library('jenkins-shared-library') _

buildAndDeployMicroservice(
        language: 'java',
        buildTool: 'gradle',
        imageName: 'demo-latest',
        svcName: 'book-svc',
        rootProjectDir: "${WORKSPACE}/..",
)