name: Build and Publish Book Service Image

on:
  push:
    branches: [ master ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Build Docker image
        run: ./gradlew clean build -p book-svc

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and Push Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: docker/build-push-action@v4
        with:
          context: ./book-svc
          push: true
          tags: ghcr.io/${{ github.repository }}/bookSvc:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=https://github.com/lifeodyssey/demo
            org.opencontainers.image.revision=${{ github.sha }}
